"use client";
import { motion } from "framer-motion";

const sectionAnimation = {
  initial: { opacity: 0, y: 50 },
  whileInView: { opacity: 1, y: 0 },
  transition: { duration: 0.8, ease: "easeOut" },
  viewport: { once: true },
};

export default function CibfActivation() {
  return (
    <motion.section
      {...sectionAnimation}
      className="w-screen h-screen flex justify-center items-center p-8 box-border bg-cosmic relative"
    >
      <div className="absolute inset-0 bg-gradient-to-br from-purple-900/20 via-transparent to-blue-900/20"></div>
      <div className="w-full max-w-5xl text-center animate-fade-in-up relative z-10">
        <h2 className="text-4xl md:text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400 mb-8 font-space">
          The CIBF 2025 Activation
        </h2>
        <div className="glass-dark p-12 rounded-3xl animate-glow">
          <p className="text-2xl text-slate-300 leading-relaxed mb-8">
            An <span className="text-purple-400 font-bold">immersive booth</span> with surreal soundscape and visuals.
          </p>
          <div className="grid md:grid-cols-2 gap-8">
            <div className="glass p-6 rounded-xl">
              <h4 className="text-purple-400 font-semibold text-xl mb-3">Limited Edition AI-Art Merchandise</h4>
              <p className="text-slate-300">Exclusive collectibles generated by AI</p>
            </div>
            <div className="glass p-6 rounded-xl">
              <h4 className="text-pink-400 font-semibold text-xl mb-3">AR Scenes & QR Unlocks</h4>
              <p className="text-slate-300">Interactive experiences via QR codes</p>
            </div>
          </div>
        </div>
      </div>
    </motion.section>
  );
}
